# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小牛博客
subtitle: 每天进步一点点!
description: '一个大学生的博客，记录学习，记录成长，分享生活！'
keywords: Blog,博客,Java,js,JavaScript,C,C++,SQL,Python,Git
author: Dreamy.NXD
language: zh-CN
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://niuxvdong.top
root: /
#permalink: :year/:month/:day/:title/
permalink: posts/:abbrlink.html  # 此处可以自己设置，也可以直接使用 :/abbrlink
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# 需要忽略文件路径
skip_render: 

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Agate/Atom One Dark Reasonable/Atom One Dark/Atom One Light/Dark/Dracula/Gml/Hopscotch/Qtcreator Dark/School Book/Xt 256/A 11 Y Dark
highlight:
  enable: false   
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Live2D
# https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: false
  # enable: false
  # scriptFrom: local # 默认
  # pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  # pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  # pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  # tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  # debug: false # 调试, 是否在控制台输出日志
#  model:
#    use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  # display:
    # position: left
    # width: 150
    # height: 300
  # mobile:
    # show: true # 手机中是否展示
    
aplayer:
	meting: true

dplayer:
    enable: true
    
#添加emoji表情支持 https://npm.taobao.org/package/hexo-filter-github-emojis
githubEmojis: 
    enable: true 
    className: github-emoji 
    inject: true 
    styles: 
    customEmojis:
    

# 代码高亮主题切换 https://github.com/ele828/hexo-prism-plugin
# 可选主题：
# coy,dark,okaidia,-tomorrow,ghcolors,hopscotch
prism_plugin: 
    mode: 'preprocess' # realtime/preprocess 
    theme: 'tomorrow'  #default
    line_number: true  # default false 
    custom_css:
    
# Hexo搜索插件 https://github.com/wzpan/hexo-generator-search
search:
    path: search.xml
    field: post
  
  
# 中文链接转拼音 https://github.com/viko16/hexo-permalink-pinyin
# permalink_pinyin:
    # enable: true
    # separator: '-' # default: '-'

# RSS https://github.com/hexojs/hexo-generator-feed  
feed: 
    type: atom 
    path: atom.xml 
    limit: 20 
    hub: 
    content: 
    content_limit: 140 
    content_limit_delim: ' ' 
    order_by: -date
    
    
    
# 文章生成永久链接 https://github.com/rozbo/hexo-abbrlink  
abbrlink: 
    alg: crc16 #算法： crc16(default) and crc32 
    rep: dec #进制： dec(default) and hex: dec #输出进制：十进制和十六进制，默认为10进制。丨dec为十进制，hex为十六进制


# 图片懒加载 https://github.com/Troy-Yang/hexo-lazyload-image
lazyload: 
    enable: true # 是否开启图片懒加载 
    onlypost: true # 是否只对文章的图片做懒加载 
    loadingImg: https://cdn.jsdelivr.net/gh/niuxvdong/images/img/loading.gif

# hexo-douban
# douban: 
    # user: 210398358 #这个需要修改为你个人的id 
    # builtin: false #如果想生成豆瓣页面，这个需要设置为true 
    # book: 
        # title: '我的书单' 
        # quote: '书看的慢，认真读才是享受！' 
    # movie: 
        # title: '我的影单' 
        # quote: '那些年我看过的电影' 
    # timeout: 10000
    
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
    
deploy:
- type: 'git'
  repo: 
    github: git@github.com:niuxvdong/niuxvdong.github.io.git,master
    coding: git@e.coding.net:niuxvdong/blog.git,master
    #gitee: git@gitee.com:niuxvdong/blog.git,master
- type: baidu_url_submitter    

# - type: upyun
  # serviceName: nxd-upyun-blog #服务名称
  # operatorName: niuxvdong #操作员名称
  # operatorPassword: CBCwIKA8jN6ypyWtePyXfOM68VscOJa8 #操作员密码
  # path: / #上传目录(选填，默认为根目录)


# hexo-baidu-url-submit 百度主动推送 
baidu_url_submit: 
    count: 80 # 提交最新的一个链接 
    host: niuxvdong.top # 在百度站长平台中注册的域名 
    token: WAtgzOp9lVQXjDi3 # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里! 
    path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里

# - type: upyun
  # bucket: nius-blog
  # operator: niuxvdong
  # password: CBCwIKA8jN6ypyWtePyXfOM68VscOJa8
  # endpoint: v0.api.upyun.com
  # secret: secret
  # try_times: 5
  # ignore_path_re:
    # dir: null
    # file: ".DS_Store$"
    
    
backup:
  type: git
  # theme: hexo-theme-matery
  theme: Butterfly
  message: Back up my niuxvdong.top blog
  repository:
    github: git@github.com:niuxvdong/niuxvdong.github.io.git,backup
    coding: git@e.coding.net:niuxvdong/blog.git,backup
  
  


  
  
  